// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

// Create my function that does everything.
function myFunction(n) {
    // 1. Pupulate an array that consists of pentagonal numbers.
    var myPnArray = [];
    // PnArray(n);
    function PnArray(n) {
        for (i = 1; i < n + 1; i++) {
            var P = i * (3 * i - 1) / 2;
            myPnArray.push(P);
        }
        console.log("P" + n + " is: ", myPnArray[n - 1]);
        console.log("The complete array is: ", myPnArray);
    }
    PnArray(n);

    // Now to generate an array of arrays.
    // var arrayOfArrays = [];
    // function arrayMaker (a,b){
    //     var dummyArray = [];
    //     dummyArray.push(a);
    //     dummyArray.push(b);
    //     arrayOfArrays.push(dummyArray)
    // }
    myPnArray.forEach(element => {
        console.log("Hello");
    });
    // for (i = 0; i < myPnArray.length; i++) {
        // console.log("Hello");
        // console.log("the PNArray is ", myPnArray.length);
    // }

    
}
myFunction(4);
// myFunction(2);
